"""Export only public ABIs; no RPC, wallet, or network is used."""
import json
from pathlib import Path

names = ["LoopConfig", "LoopReceipt", "LoopPosition"]
abis = {name: json.loads((Path("out") / (name + ".sol") / (name + ".json")).read_text())["abi"] for name in names}
Path("web/abi.js").write_text("// Generated by scripts/export_web_abi.py after forge build.\nwindow.LOOP_ABI = " + json.dumps(abis, separators=(",", ":")) + ";\n")
